//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Ecat.Data.BbWs.BbCourseMembership {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CourseMembership.WSSOAP11Binding", Namespace="http://coursemembership.ws.blackboard/")]
    public partial class CourseMembershipWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback deleteGroupMembershipOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGroupMembershipOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCourseRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCourseMembershipOperationCompleted;
        
        private System.Threading.SendOrPostCallback getServerVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback initializeCourseMembershipWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveCourseMembershipOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveGroupMembershipOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteCourseMembershipOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CourseMembershipWS() {
            this.Url = global::Ecat.Data.Properties.Settings.Default.Ecat_Data_com_blackboard_barnescenter_CourseMembership_WS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event deleteGroupMembershipCompletedEventHandler deleteGroupMembershipCompleted;
        
        /// <remarks/>
        public event getGroupMembershipCompletedEventHandler getGroupMembershipCompleted;
        
        /// <remarks/>
        public event getCourseRolesCompletedEventHandler getCourseRolesCompleted;
        
        /// <remarks/>
        public event getCourseMembershipCompletedEventHandler getCourseMembershipCompleted;
        
        /// <remarks/>
        public event getServerVersionCompletedEventHandler getServerVersionCompleted;
        
        /// <remarks/>
        public event initializeCourseMembershipWSCompletedEventHandler initializeCourseMembershipWSCompleted;
        
        /// <remarks/>
        public event saveCourseMembershipCompletedEventHandler saveCourseMembershipCompleted;
        
        /// <remarks/>
        public event saveGroupMembershipCompletedEventHandler saveGroupMembershipCompleted;
        
        /// <remarks/>
        public event deleteCourseMembershipCompletedEventHandler deleteCourseMembershipCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("deleteGroupMembership", RequestNamespace="http://coursemembership.ws.blackboard", ResponseNamespace="http://coursemembership.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] deleteGroupMembership([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string courseId, [System.Xml.Serialization.XmlElementAttribute("ids", IsNullable=true)] string[] ids) {
            object[] results = this.Invoke("deleteGroupMembership", new object[] {
                        courseId,
                        ids});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void deleteGroupMembershipAsync(string courseId, string[] ids) {
            this.deleteGroupMembershipAsync(courseId, ids, null);
        }
        
        /// <remarks/>
        public void deleteGroupMembershipAsync(string courseId, string[] ids, object userState) {
            if ((this.deleteGroupMembershipOperationCompleted == null)) {
                this.deleteGroupMembershipOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteGroupMembershipOperationCompleted);
            }
            this.InvokeAsync("deleteGroupMembership", new object[] {
                        courseId,
                        ids}, this.deleteGroupMembershipOperationCompleted, userState);
        }
        
        private void OndeleteGroupMembershipOperationCompleted(object arg) {
            if ((this.deleteGroupMembershipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteGroupMembershipCompleted(this, new deleteGroupMembershipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getGroupMembership", RequestNamespace="http://coursemembership.ws.blackboard", ResponseNamespace="http://coursemembership.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public GroupMembershipVO[] getGroupMembership([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string courseId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MembershipFilter f) {
            object[] results = this.Invoke("getGroupMembership", new object[] {
                        courseId,
                        f});
            return ((GroupMembershipVO[])(results[0]));
        }
        
        /// <remarks/>
        public void getGroupMembershipAsync(string courseId, MembershipFilter f) {
            this.getGroupMembershipAsync(courseId, f, null);
        }
        
        /// <remarks/>
        public void getGroupMembershipAsync(string courseId, MembershipFilter f, object userState) {
            if ((this.getGroupMembershipOperationCompleted == null)) {
                this.getGroupMembershipOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGroupMembershipOperationCompleted);
            }
            this.InvokeAsync("getGroupMembership", new object[] {
                        courseId,
                        f}, this.getGroupMembershipOperationCompleted, userState);
        }
        
        private void OngetGroupMembershipOperationCompleted(object arg) {
            if ((this.getGroupMembershipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGroupMembershipCompleted(this, new getGroupMembershipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getCourseRoles", RequestNamespace="http://coursemembership.ws.blackboard", ResponseNamespace="http://coursemembership.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CourseMembershipRoleVO[] getCourseRoles([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute("roleIds", Namespace="http://coursemembership.ws.blackboard/xsd")] string[] f) {
            object[] results = this.Invoke("getCourseRoles", new object[] {
                        f});
            return ((CourseMembershipRoleVO[])(results[0]));
        }
        
        /// <remarks/>
        public void getCourseRolesAsync(string[] f) {
            this.getCourseRolesAsync(f, null);
        }
        
        /// <remarks/>
        public void getCourseRolesAsync(string[] f, object userState) {
            if ((this.getCourseRolesOperationCompleted == null)) {
                this.getCourseRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCourseRolesOperationCompleted);
            }
            this.InvokeAsync("getCourseRoles", new object[] {
                        f}, this.getCourseRolesOperationCompleted, userState);
        }
        
        private void OngetCourseRolesOperationCompleted(object arg) {
            if ((this.getCourseRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCourseRolesCompleted(this, new getCourseRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getCourseMembership", RequestNamespace="http://coursemembership.ws.blackboard", ResponseNamespace="http://coursemembership.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CourseMembershipVO[] getCourseMembership([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string courseId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MembershipFilter f) {
            object[] results = this.Invoke("getCourseMembership", new object[] {
                        courseId,
                        f});
            return ((CourseMembershipVO[])(results[0]));
        }
        
        /// <remarks/>
        public void getCourseMembershipAsync(string courseId, MembershipFilter f) {
            this.getCourseMembershipAsync(courseId, f, null);
        }
        
        /// <remarks/>
        public void getCourseMembershipAsync(string courseId, MembershipFilter f, object userState) {
            if ((this.getCourseMembershipOperationCompleted == null)) {
                this.getCourseMembershipOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCourseMembershipOperationCompleted);
            }
            this.InvokeAsync("getCourseMembership", new object[] {
                        courseId,
                        f}, this.getCourseMembershipOperationCompleted, userState);
        }
        
        private void OngetCourseMembershipOperationCompleted(object arg) {
            if ((this.getCourseMembershipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCourseMembershipCompleted(this, new getCourseMembershipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getServerVersion", RequestNamespace="http://coursemembership.ws.blackboard", ResponseNamespace="http://coursemembership.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public VersionVO getServerVersion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] VersionVO unused) {
            object[] results = this.Invoke("getServerVersion", new object[] {
                        unused});
            return ((VersionVO)(results[0]));
        }
        
        /// <remarks/>
        public void getServerVersionAsync(VersionVO unused) {
            this.getServerVersionAsync(unused, null);
        }
        
        /// <remarks/>
        public void getServerVersionAsync(VersionVO unused, object userState) {
            if ((this.getServerVersionOperationCompleted == null)) {
                this.getServerVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServerVersionOperationCompleted);
            }
            this.InvokeAsync("getServerVersion", new object[] {
                        unused}, this.getServerVersionOperationCompleted, userState);
        }
        
        private void OngetServerVersionOperationCompleted(object arg) {
            if ((this.getServerVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getServerVersionCompleted(this, new getServerVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("initializeCourseMembershipWS", RequestNamespace="http://coursemembership.ws.blackboard", ResponseNamespace="http://coursemembership.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void initializeCourseMembershipWS(bool ignore, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ignoreSpecified, out bool @return, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool returnSpecified) {
            object[] results = this.Invoke("initializeCourseMembershipWS", new object[] {
                        ignore,
                        ignoreSpecified});
            @return = ((bool)(results[0]));
            returnSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void initializeCourseMembershipWSAsync(bool ignore, bool ignoreSpecified) {
            this.initializeCourseMembershipWSAsync(ignore, ignoreSpecified, null);
        }
        
        /// <remarks/>
        public void initializeCourseMembershipWSAsync(bool ignore, bool ignoreSpecified, object userState) {
            if ((this.initializeCourseMembershipWSOperationCompleted == null)) {
                this.initializeCourseMembershipWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OninitializeCourseMembershipWSOperationCompleted);
            }
            this.InvokeAsync("initializeCourseMembershipWS", new object[] {
                        ignore,
                        ignoreSpecified}, this.initializeCourseMembershipWSOperationCompleted, userState);
        }
        
        private void OninitializeCourseMembershipWSOperationCompleted(object arg) {
            if ((this.initializeCourseMembershipWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.initializeCourseMembershipWSCompleted(this, new initializeCourseMembershipWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("saveCourseMembership", RequestNamespace="http://coursemembership.ws.blackboard", ResponseNamespace="http://coursemembership.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] saveCourseMembership([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string courseId, [System.Xml.Serialization.XmlElementAttribute("cmArray", IsNullable=true)] CourseMembershipVO[] cmArray) {
            object[] results = this.Invoke("saveCourseMembership", new object[] {
                        courseId,
                        cmArray});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void saveCourseMembershipAsync(string courseId, CourseMembershipVO[] cmArray) {
            this.saveCourseMembershipAsync(courseId, cmArray, null);
        }
        
        /// <remarks/>
        public void saveCourseMembershipAsync(string courseId, CourseMembershipVO[] cmArray, object userState) {
            if ((this.saveCourseMembershipOperationCompleted == null)) {
                this.saveCourseMembershipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveCourseMembershipOperationCompleted);
            }
            this.InvokeAsync("saveCourseMembership", new object[] {
                        courseId,
                        cmArray}, this.saveCourseMembershipOperationCompleted, userState);
        }
        
        private void OnsaveCourseMembershipOperationCompleted(object arg) {
            if ((this.saveCourseMembershipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveCourseMembershipCompleted(this, new saveCourseMembershipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("saveGroupMembership", RequestNamespace="http://coursemembership.ws.blackboard", ResponseNamespace="http://coursemembership.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] saveGroupMembership([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string courseId, [System.Xml.Serialization.XmlElementAttribute("g", IsNullable=true)] GroupMembershipVO[] g) {
            object[] results = this.Invoke("saveGroupMembership", new object[] {
                        courseId,
                        g});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void saveGroupMembershipAsync(string courseId, GroupMembershipVO[] g) {
            this.saveGroupMembershipAsync(courseId, g, null);
        }
        
        /// <remarks/>
        public void saveGroupMembershipAsync(string courseId, GroupMembershipVO[] g, object userState) {
            if ((this.saveGroupMembershipOperationCompleted == null)) {
                this.saveGroupMembershipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveGroupMembershipOperationCompleted);
            }
            this.InvokeAsync("saveGroupMembership", new object[] {
                        courseId,
                        g}, this.saveGroupMembershipOperationCompleted, userState);
        }
        
        private void OnsaveGroupMembershipOperationCompleted(object arg) {
            if ((this.saveGroupMembershipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveGroupMembershipCompleted(this, new saveGroupMembershipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("deleteCourseMembership", RequestNamespace="http://coursemembership.ws.blackboard", ResponseNamespace="http://coursemembership.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] deleteCourseMembership([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string courseId, [System.Xml.Serialization.XmlElementAttribute("ids", IsNullable=true)] string[] ids) {
            object[] results = this.Invoke("deleteCourseMembership", new object[] {
                        courseId,
                        ids});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void deleteCourseMembershipAsync(string courseId, string[] ids) {
            this.deleteCourseMembershipAsync(courseId, ids, null);
        }
        
        /// <remarks/>
        public void deleteCourseMembershipAsync(string courseId, string[] ids, object userState) {
            if ((this.deleteCourseMembershipOperationCompleted == null)) {
                this.deleteCourseMembershipOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteCourseMembershipOperationCompleted);
            }
            this.InvokeAsync("deleteCourseMembership", new object[] {
                        courseId,
                        ids}, this.deleteCourseMembershipOperationCompleted, userState);
        }
        
        private void OndeleteCourseMembershipOperationCompleted(object arg) {
            if ((this.deleteCourseMembershipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCourseMembershipCompleted(this, new deleteCourseMembershipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coursemembership.ws.blackboard/xsd")]
    public partial class MembershipFilter {
        
        private string[] courseIdsField;
        
        private string[] courseMembershipIdsField;
        
        private string[] expansionDataField;
        
        private int filterTypeField;
        
        private bool filterTypeFieldSpecified;
        
        private string[] groupIdsField;
        
        private string[] groupMembershipIdsField;
        
        private string[] roleIdsField;
        
        private string[] userIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("courseIds", IsNullable=true)]
        public string[] courseIds {
            get {
                return this.courseIdsField;
            }
            set {
                this.courseIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("courseMembershipIds", IsNullable=true)]
        public string[] courseMembershipIds {
            get {
                return this.courseMembershipIdsField;
            }
            set {
                this.courseMembershipIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expansionData", IsNullable=true)]
        public string[] expansionData {
            get {
                return this.expansionDataField;
            }
            set {
                this.expansionDataField = value;
            }
        }
        
        /// <remarks/>
        public int filterType {
            get {
                return this.filterTypeField;
            }
            set {
                this.filterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool filterTypeSpecified {
            get {
                return this.filterTypeFieldSpecified;
            }
            set {
                this.filterTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("groupIds", IsNullable=true)]
        public string[] groupIds {
            get {
                return this.groupIdsField;
            }
            set {
                this.groupIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("groupMembershipIds", IsNullable=true)]
        public string[] groupMembershipIds {
            get {
                return this.groupMembershipIdsField;
            }
            set {
                this.groupMembershipIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("roleIds", IsNullable=true)]
        public string[] roleIds {
            get {
                return this.roleIdsField;
            }
            set {
                this.roleIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userIds", IsNullable=true)]
        public string[] userIds {
            get {
                return this.userIdsField;
            }
            set {
                this.userIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.platform.blackboard/xsd")]
    public partial class VersionVO {
        
        private long versionField;
        
        private bool versionFieldSpecified;
        
        /// <remarks/>
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified {
            get {
                return this.versionFieldSpecified;
            }
            set {
                this.versionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coursemembership.ws.blackboard/xsd")]
    public partial class CourseMembershipVO {
        
        private System.Nullable<bool> availableField;
        
        private bool availableFieldSpecified;
        
        private string courseIdField;
        
        private string dataSourceIdField;
        
        private long enrollmentDateField;
        
        private bool enrollmentDateFieldSpecified;
        
        private string[] expansionDataField;
        
        private System.Nullable<bool> hasCartridgeAccessField;
        
        private bool hasCartridgeAccessFieldSpecified;
        
        private string idField;
        
        private string imageFileField;
        
        private string roleIdField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> available {
            get {
                return this.availableField;
            }
            set {
                this.availableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool availableSpecified {
            get {
                return this.availableFieldSpecified;
            }
            set {
                this.availableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string courseId {
            get {
                return this.courseIdField;
            }
            set {
                this.courseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dataSourceId {
            get {
                return this.dataSourceIdField;
            }
            set {
                this.dataSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public long enrollmentDate {
            get {
                return this.enrollmentDateField;
            }
            set {
                this.enrollmentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enrollmentDateSpecified {
            get {
                return this.enrollmentDateFieldSpecified;
            }
            set {
                this.enrollmentDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expansionData", IsNullable=true)]
        public string[] expansionData {
            get {
                return this.expansionDataField;
            }
            set {
                this.expansionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> hasCartridgeAccess {
            get {
                return this.hasCartridgeAccessField;
            }
            set {
                this.hasCartridgeAccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hasCartridgeAccessSpecified {
            get {
                return this.hasCartridgeAccessFieldSpecified;
            }
            set {
                this.hasCartridgeAccessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string imageFile {
            get {
                return this.imageFileField;
            }
            set {
                this.imageFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string roleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coursemembership.ws.blackboard/xsd")]
    public partial class CourseMembershipRoleVO {
        
        private string courseRoleDescriptionField;
        
        private System.Nullable<bool> defaultRoleField;
        
        private bool defaultRoleFieldSpecified;
        
        private string[] expansionDataField;
        
        private string orgRoleDescriptionField;
        
        private string roleIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string courseRoleDescription {
            get {
                return this.courseRoleDescriptionField;
            }
            set {
                this.courseRoleDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> defaultRole {
            get {
                return this.defaultRoleField;
            }
            set {
                this.defaultRoleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool defaultRoleSpecified {
            get {
                return this.defaultRoleFieldSpecified;
            }
            set {
                this.defaultRoleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expansionData", IsNullable=true)]
        public string[] expansionData {
            get {
                return this.expansionDataField;
            }
            set {
                this.expansionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orgRoleDescription {
            get {
                return this.orgRoleDescriptionField;
            }
            set {
                this.orgRoleDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string roleIdentifier {
            get {
                return this.roleIdentifierField;
            }
            set {
                this.roleIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coursemembership.ws.blackboard/xsd")]
    public partial class GroupMembershipVO {
        
        private string courseMembershipIdField;
        
        private string[] expansionDataField;
        
        private string groupIdField;
        
        private string groupMembershipIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string courseMembershipId {
            get {
                return this.courseMembershipIdField;
            }
            set {
                this.courseMembershipIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expansionData", IsNullable=true)]
        public string[] expansionData {
            get {
                return this.expansionDataField;
            }
            set {
                this.expansionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string groupMembershipId {
            get {
                return this.groupMembershipIdField;
            }
            set {
                this.groupMembershipIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void deleteGroupMembershipCompletedEventHandler(object sender, deleteGroupMembershipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteGroupMembershipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteGroupMembershipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getGroupMembershipCompletedEventHandler(object sender, getGroupMembershipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGroupMembershipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGroupMembershipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GroupMembershipVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GroupMembershipVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCourseRolesCompletedEventHandler(object sender, getCourseRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCourseRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCourseRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseMembershipRoleVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseMembershipRoleVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCourseMembershipCompletedEventHandler(object sender, getCourseMembershipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCourseMembershipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCourseMembershipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseMembershipVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseMembershipVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getServerVersionCompletedEventHandler(object sender, getServerVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getServerVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getServerVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VersionVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VersionVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void initializeCourseMembershipWSCompletedEventHandler(object sender, initializeCourseMembershipWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class initializeCourseMembershipWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal initializeCourseMembershipWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool @return {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool returnSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void saveCourseMembershipCompletedEventHandler(object sender, saveCourseMembershipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveCourseMembershipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveCourseMembershipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void saveGroupMembershipCompletedEventHandler(object sender, saveGroupMembershipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveGroupMembershipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveGroupMembershipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void deleteCourseMembershipCompletedEventHandler(object sender, deleteCourseMembershipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteCourseMembershipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteCourseMembershipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591