//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Ecat.Data.BbWs.BbUser {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="User.WSSOAP11Binding", Namespace="http://user.ws.blackboard/")]
    public partial class UserWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback changeUserBatchUidOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSystemRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveObserverAssociationOperationCompleted;
        
        private System.Threading.SendOrPostCallback getServerVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserInstitutionRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback changeUserDataSourceIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteObserverAssociationOperationCompleted;
        
        private System.Threading.SendOrPostCallback initializeUserWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteAddressBookEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveAddressBookEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteUserByInstitutionRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInstitutionRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAddressBookEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback getObserveeOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserWS() {
            this.Url = global::Ecat.Data.Properties.Settings.Default.Ecat_Data_BbWs_BbUser_User_WS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event changeUserBatchUidCompletedEventHandler changeUserBatchUidCompleted;
        
        /// <remarks/>
        public event getSystemRolesCompletedEventHandler getSystemRolesCompleted;
        
        /// <remarks/>
        public event getUserCompletedEventHandler getUserCompleted;
        
        /// <remarks/>
        public event saveObserverAssociationCompletedEventHandler saveObserverAssociationCompleted;
        
        /// <remarks/>
        public event getServerVersionCompletedEventHandler getServerVersionCompleted;
        
        /// <remarks/>
        public event getUserInstitutionRolesCompletedEventHandler getUserInstitutionRolesCompleted;
        
        /// <remarks/>
        public event changeUserDataSourceIdCompletedEventHandler changeUserDataSourceIdCompleted;
        
        /// <remarks/>
        public event deleteObserverAssociationCompletedEventHandler deleteObserverAssociationCompleted;
        
        /// <remarks/>
        public event initializeUserWSCompletedEventHandler initializeUserWSCompleted;
        
        /// <remarks/>
        public event deleteAddressBookEntryCompletedEventHandler deleteAddressBookEntryCompleted;
        
        /// <remarks/>
        public event saveAddressBookEntryCompletedEventHandler saveAddressBookEntryCompleted;
        
        /// <remarks/>
        public event deleteUserByInstitutionRoleCompletedEventHandler deleteUserByInstitutionRoleCompleted;
        
        /// <remarks/>
        public event deleteUserCompletedEventHandler deleteUserCompleted;
        
        /// <remarks/>
        public event getInstitutionRolesCompletedEventHandler getInstitutionRolesCompleted;
        
        /// <remarks/>
        public event getAddressBookEntryCompletedEventHandler getAddressBookEntryCompleted;
        
        /// <remarks/>
        public event getObserveeCompletedEventHandler getObserveeCompleted;
        
        /// <remarks/>
        public event saveUserCompletedEventHandler saveUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("changeUserBatchUid", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void changeUserBatchUid([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string originalBatchUid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string batchUid, out bool @return, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool returnSpecified) {
            object[] results = this.Invoke("changeUserBatchUid", new object[] {
                        originalBatchUid,
                        batchUid});
            @return = ((bool)(results[0]));
            returnSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void changeUserBatchUidAsync(string originalBatchUid, string batchUid) {
            this.changeUserBatchUidAsync(originalBatchUid, batchUid, null);
        }
        
        /// <remarks/>
        public void changeUserBatchUidAsync(string originalBatchUid, string batchUid, object userState) {
            if ((this.changeUserBatchUidOperationCompleted == null)) {
                this.changeUserBatchUidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangeUserBatchUidOperationCompleted);
            }
            this.InvokeAsync("changeUserBatchUid", new object[] {
                        originalBatchUid,
                        batchUid}, this.changeUserBatchUidOperationCompleted, userState);
        }
        
        private void OnchangeUserBatchUidOperationCompleted(object arg) {
            if ((this.changeUserBatchUidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changeUserBatchUidCompleted(this, new changeUserBatchUidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getSystemRoles", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] getSystemRoles([System.Xml.Serialization.XmlElementAttribute("filter", IsNullable=true)] string[] filter) {
            object[] results = this.Invoke("getSystemRoles", new object[] {
                        filter});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getSystemRolesAsync(string[] filter) {
            this.getSystemRolesAsync(filter, null);
        }
        
        /// <remarks/>
        public void getSystemRolesAsync(string[] filter, object userState) {
            if ((this.getSystemRolesOperationCompleted == null)) {
                this.getSystemRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSystemRolesOperationCompleted);
            }
            this.InvokeAsync("getSystemRoles", new object[] {
                        filter}, this.getSystemRolesOperationCompleted, userState);
        }
        
        private void OngetSystemRolesOperationCompleted(object arg) {
            if ((this.getSystemRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSystemRolesCompleted(this, new getSystemRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getUser", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public UserVO[] getUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UserFilter filter) {
            object[] results = this.Invoke("getUser", new object[] {
                        filter});
            return ((UserVO[])(results[0]));
        }
        
        /// <remarks/>
        public void getUserAsync(UserFilter filter) {
            this.getUserAsync(filter, null);
        }
        
        /// <remarks/>
        public void getUserAsync(UserFilter filter, object userState) {
            if ((this.getUserOperationCompleted == null)) {
                this.getUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserOperationCompleted);
            }
            this.InvokeAsync("getUser", new object[] {
                        filter}, this.getUserOperationCompleted, userState);
        }
        
        private void OngetUserOperationCompleted(object arg) {
            if ((this.getUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserCompleted(this, new getUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("saveObserverAssociation", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] saveObserverAssociation([System.Xml.Serialization.XmlElementAttribute("association", IsNullable=true)] ObserverAssociationVO[] association) {
            object[] results = this.Invoke("saveObserverAssociation", new object[] {
                        association});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void saveObserverAssociationAsync(ObserverAssociationVO[] association) {
            this.saveObserverAssociationAsync(association, null);
        }
        
        /// <remarks/>
        public void saveObserverAssociationAsync(ObserverAssociationVO[] association, object userState) {
            if ((this.saveObserverAssociationOperationCompleted == null)) {
                this.saveObserverAssociationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveObserverAssociationOperationCompleted);
            }
            this.InvokeAsync("saveObserverAssociation", new object[] {
                        association}, this.saveObserverAssociationOperationCompleted, userState);
        }
        
        private void OnsaveObserverAssociationOperationCompleted(object arg) {
            if ((this.saveObserverAssociationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveObserverAssociationCompleted(this, new saveObserverAssociationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getServerVersion", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public VersionVO getServerVersion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] VersionVO unused) {
            object[] results = this.Invoke("getServerVersion", new object[] {
                        unused});
            return ((VersionVO)(results[0]));
        }
        
        /// <remarks/>
        public void getServerVersionAsync(VersionVO unused) {
            this.getServerVersionAsync(unused, null);
        }
        
        /// <remarks/>
        public void getServerVersionAsync(VersionVO unused, object userState) {
            if ((this.getServerVersionOperationCompleted == null)) {
                this.getServerVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServerVersionOperationCompleted);
            }
            this.InvokeAsync("getServerVersion", new object[] {
                        unused}, this.getServerVersionOperationCompleted, userState);
        }
        
        private void OngetServerVersionOperationCompleted(object arg) {
            if ((this.getServerVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getServerVersionCompleted(this, new getServerVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getUserInstitutionRoles", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public UserRoleVO[] getUserInstitutionRoles([System.Xml.Serialization.XmlElementAttribute("userId", IsNullable=true)] string[] userId) {
            object[] results = this.Invoke("getUserInstitutionRoles", new object[] {
                        userId});
            return ((UserRoleVO[])(results[0]));
        }
        
        /// <remarks/>
        public void getUserInstitutionRolesAsync(string[] userId) {
            this.getUserInstitutionRolesAsync(userId, null);
        }
        
        /// <remarks/>
        public void getUserInstitutionRolesAsync(string[] userId, object userState) {
            if ((this.getUserInstitutionRolesOperationCompleted == null)) {
                this.getUserInstitutionRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserInstitutionRolesOperationCompleted);
            }
            this.InvokeAsync("getUserInstitutionRoles", new object[] {
                        userId}, this.getUserInstitutionRolesOperationCompleted, userState);
        }
        
        private void OngetUserInstitutionRolesOperationCompleted(object arg) {
            if ((this.getUserInstitutionRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserInstitutionRolesCompleted(this, new getUserInstitutionRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("changeUserDataSourceId", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void changeUserDataSourceId([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string dataSourceId, out bool @return, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool returnSpecified) {
            object[] results = this.Invoke("changeUserDataSourceId", new object[] {
                        userId,
                        dataSourceId});
            @return = ((bool)(results[0]));
            returnSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void changeUserDataSourceIdAsync(string userId, string dataSourceId) {
            this.changeUserDataSourceIdAsync(userId, dataSourceId, null);
        }
        
        /// <remarks/>
        public void changeUserDataSourceIdAsync(string userId, string dataSourceId, object userState) {
            if ((this.changeUserDataSourceIdOperationCompleted == null)) {
                this.changeUserDataSourceIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangeUserDataSourceIdOperationCompleted);
            }
            this.InvokeAsync("changeUserDataSourceId", new object[] {
                        userId,
                        dataSourceId}, this.changeUserDataSourceIdOperationCompleted, userState);
        }
        
        private void OnchangeUserDataSourceIdOperationCompleted(object arg) {
            if ((this.changeUserDataSourceIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changeUserDataSourceIdCompleted(this, new changeUserDataSourceIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("deleteObserverAssociation", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] deleteObserverAssociation([System.Xml.Serialization.XmlElementAttribute("association", IsNullable=true)] ObserverAssociationVO[] association) {
            object[] results = this.Invoke("deleteObserverAssociation", new object[] {
                        association});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void deleteObserverAssociationAsync(ObserverAssociationVO[] association) {
            this.deleteObserverAssociationAsync(association, null);
        }
        
        /// <remarks/>
        public void deleteObserverAssociationAsync(ObserverAssociationVO[] association, object userState) {
            if ((this.deleteObserverAssociationOperationCompleted == null)) {
                this.deleteObserverAssociationOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteObserverAssociationOperationCompleted);
            }
            this.InvokeAsync("deleteObserverAssociation", new object[] {
                        association}, this.deleteObserverAssociationOperationCompleted, userState);
        }
        
        private void OndeleteObserverAssociationOperationCompleted(object arg) {
            if ((this.deleteObserverAssociationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteObserverAssociationCompleted(this, new deleteObserverAssociationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("initializeUserWS", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void initializeUserWS(bool ignore, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ignoreSpecified, out bool @return, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool returnSpecified) {
            object[] results = this.Invoke("initializeUserWS", new object[] {
                        ignore,
                        ignoreSpecified});
            @return = ((bool)(results[0]));
            returnSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void initializeUserWSAsync(bool ignore, bool ignoreSpecified) {
            this.initializeUserWSAsync(ignore, ignoreSpecified, null);
        }
        
        /// <remarks/>
        public void initializeUserWSAsync(bool ignore, bool ignoreSpecified, object userState) {
            if ((this.initializeUserWSOperationCompleted == null)) {
                this.initializeUserWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OninitializeUserWSOperationCompleted);
            }
            this.InvokeAsync("initializeUserWS", new object[] {
                        ignore,
                        ignoreSpecified}, this.initializeUserWSOperationCompleted, userState);
        }
        
        private void OninitializeUserWSOperationCompleted(object arg) {
            if ((this.initializeUserWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.initializeUserWSCompleted(this, new initializeUserWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("deleteAddressBookEntry", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] deleteAddressBookEntry([System.Xml.Serialization.XmlElementAttribute("entryId", IsNullable=true)] string[] entryId) {
            object[] results = this.Invoke("deleteAddressBookEntry", new object[] {
                        entryId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void deleteAddressBookEntryAsync(string[] entryId) {
            this.deleteAddressBookEntryAsync(entryId, null);
        }
        
        /// <remarks/>
        public void deleteAddressBookEntryAsync(string[] entryId, object userState) {
            if ((this.deleteAddressBookEntryOperationCompleted == null)) {
                this.deleteAddressBookEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteAddressBookEntryOperationCompleted);
            }
            this.InvokeAsync("deleteAddressBookEntry", new object[] {
                        entryId}, this.deleteAddressBookEntryOperationCompleted, userState);
        }
        
        private void OndeleteAddressBookEntryOperationCompleted(object arg) {
            if ((this.deleteAddressBookEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteAddressBookEntryCompleted(this, new deleteAddressBookEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("saveAddressBookEntry", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] saveAddressBookEntry([System.Xml.Serialization.XmlElementAttribute("user", IsNullable=true)] AddressBookEntryVO[] user) {
            object[] results = this.Invoke("saveAddressBookEntry", new object[] {
                        user});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void saveAddressBookEntryAsync(AddressBookEntryVO[] user) {
            this.saveAddressBookEntryAsync(user, null);
        }
        
        /// <remarks/>
        public void saveAddressBookEntryAsync(AddressBookEntryVO[] user, object userState) {
            if ((this.saveAddressBookEntryOperationCompleted == null)) {
                this.saveAddressBookEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveAddressBookEntryOperationCompleted);
            }
            this.InvokeAsync("saveAddressBookEntry", new object[] {
                        user}, this.saveAddressBookEntryOperationCompleted, userState);
        }
        
        private void OnsaveAddressBookEntryOperationCompleted(object arg) {
            if ((this.saveAddressBookEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveAddressBookEntryCompleted(this, new saveAddressBookEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("deleteUserByInstitutionRole", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] deleteUserByInstitutionRole([System.Xml.Serialization.XmlElementAttribute("insRoleId", IsNullable=true)] string[] insRoleId) {
            object[] results = this.Invoke("deleteUserByInstitutionRole", new object[] {
                        insRoleId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void deleteUserByInstitutionRoleAsync(string[] insRoleId) {
            this.deleteUserByInstitutionRoleAsync(insRoleId, null);
        }
        
        /// <remarks/>
        public void deleteUserByInstitutionRoleAsync(string[] insRoleId, object userState) {
            if ((this.deleteUserByInstitutionRoleOperationCompleted == null)) {
                this.deleteUserByInstitutionRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteUserByInstitutionRoleOperationCompleted);
            }
            this.InvokeAsync("deleteUserByInstitutionRole", new object[] {
                        insRoleId}, this.deleteUserByInstitutionRoleOperationCompleted, userState);
        }
        
        private void OndeleteUserByInstitutionRoleOperationCompleted(object arg) {
            if ((this.deleteUserByInstitutionRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteUserByInstitutionRoleCompleted(this, new deleteUserByInstitutionRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("deleteUser", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] deleteUser([System.Xml.Serialization.XmlElementAttribute("userId", IsNullable=true)] string[] userId) {
            object[] results = this.Invoke("deleteUser", new object[] {
                        userId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void deleteUserAsync(string[] userId) {
            this.deleteUserAsync(userId, null);
        }
        
        /// <remarks/>
        public void deleteUserAsync(string[] userId, object userState) {
            if ((this.deleteUserOperationCompleted == null)) {
                this.deleteUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteUserOperationCompleted);
            }
            this.InvokeAsync("deleteUser", new object[] {
                        userId}, this.deleteUserOperationCompleted, userState);
        }
        
        private void OndeleteUserOperationCompleted(object arg) {
            if ((this.deleteUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteUserCompleted(this, new deleteUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getInstitutionRoles", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public PortalRoleVO[] getInstitutionRoles([System.Xml.Serialization.XmlElementAttribute("ids", IsNullable=true)] string[] ids) {
            object[] results = this.Invoke("getInstitutionRoles", new object[] {
                        ids});
            return ((PortalRoleVO[])(results[0]));
        }
        
        /// <remarks/>
        public void getInstitutionRolesAsync(string[] ids) {
            this.getInstitutionRolesAsync(ids, null);
        }
        
        /// <remarks/>
        public void getInstitutionRolesAsync(string[] ids, object userState) {
            if ((this.getInstitutionRolesOperationCompleted == null)) {
                this.getInstitutionRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInstitutionRolesOperationCompleted);
            }
            this.InvokeAsync("getInstitutionRoles", new object[] {
                        ids}, this.getInstitutionRolesOperationCompleted, userState);
        }
        
        private void OngetInstitutionRolesOperationCompleted(object arg) {
            if ((this.getInstitutionRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInstitutionRolesCompleted(this, new getInstitutionRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getAddressBookEntry", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public AddressBookEntryVO[] getAddressBookEntry([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UserFilter filter) {
            object[] results = this.Invoke("getAddressBookEntry", new object[] {
                        filter});
            return ((AddressBookEntryVO[])(results[0]));
        }
        
        /// <remarks/>
        public void getAddressBookEntryAsync(UserFilter filter) {
            this.getAddressBookEntryAsync(filter, null);
        }
        
        /// <remarks/>
        public void getAddressBookEntryAsync(UserFilter filter, object userState) {
            if ((this.getAddressBookEntryOperationCompleted == null)) {
                this.getAddressBookEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAddressBookEntryOperationCompleted);
            }
            this.InvokeAsync("getAddressBookEntry", new object[] {
                        filter}, this.getAddressBookEntryOperationCompleted, userState);
        }
        
        private void OngetAddressBookEntryOperationCompleted(object arg) {
            if ((this.getAddressBookEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAddressBookEntryCompleted(this, new getAddressBookEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getObservee", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public ObserverAssociationVO[] getObservee([System.Xml.Serialization.XmlElementAttribute("observerId", IsNullable=true)] string[] observerId) {
            object[] results = this.Invoke("getObservee", new object[] {
                        observerId});
            return ((ObserverAssociationVO[])(results[0]));
        }
        
        /// <remarks/>
        public void getObserveeAsync(string[] observerId) {
            this.getObserveeAsync(observerId, null);
        }
        
        /// <remarks/>
        public void getObserveeAsync(string[] observerId, object userState) {
            if ((this.getObserveeOperationCompleted == null)) {
                this.getObserveeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetObserveeOperationCompleted);
            }
            this.InvokeAsync("getObservee", new object[] {
                        observerId}, this.getObserveeOperationCompleted, userState);
        }
        
        private void OngetObserveeOperationCompleted(object arg) {
            if ((this.getObserveeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getObserveeCompleted(this, new getObserveeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("saveUser", RequestNamespace="http://user.ws.blackboard", ResponseNamespace="http://user.ws.blackboard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] saveUser([System.Xml.Serialization.XmlElementAttribute("user", IsNullable=true)] UserVO[] user) {
            object[] results = this.Invoke("saveUser", new object[] {
                        user});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void saveUserAsync(UserVO[] user) {
            this.saveUserAsync(user, null);
        }
        
        /// <remarks/>
        public void saveUserAsync(UserVO[] user, object userState) {
            if ((this.saveUserOperationCompleted == null)) {
                this.saveUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveUserOperationCompleted);
            }
            this.InvokeAsync("saveUser", new object[] {
                        user}, this.saveUserOperationCompleted, userState);
        }
        
        private void OnsaveUserOperationCompleted(object arg) {
            if ((this.saveUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveUserCompleted(this, new saveUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://user.ws.blackboard/xsd")]
    public partial class UserFilter {
        
        private bool availableField;
        
        private bool availableFieldSpecified;
        
        private string[] batchIdField;
        
        private string[] courseIdField;
        
        private string[] expansionDataField;
        
        private int filterTypeField;
        
        private bool filterTypeFieldSpecified;
        
        private string[] groupIdField;
        
        private string[] idField;
        
        private string[] nameField;
        
        private string[] systemRolesField;
        
        /// <remarks/>
        public bool available {
            get {
                return this.availableField;
            }
            set {
                this.availableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool availableSpecified {
            get {
                return this.availableFieldSpecified;
            }
            set {
                this.availableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("batchId", IsNullable=true)]
        public string[] batchId {
            get {
                return this.batchIdField;
            }
            set {
                this.batchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("courseId", IsNullable=true)]
        public string[] courseId {
            get {
                return this.courseIdField;
            }
            set {
                this.courseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expansionData", IsNullable=true)]
        public string[] expansionData {
            get {
                return this.expansionDataField;
            }
            set {
                this.expansionDataField = value;
            }
        }
        
        /// <remarks/>
        public int filterType {
            get {
                return this.filterTypeField;
            }
            set {
                this.filterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool filterTypeSpecified {
            get {
                return this.filterTypeFieldSpecified;
            }
            set {
                this.filterTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("groupId", IsNullable=true)]
        public string[] groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id", IsNullable=true)]
        public string[] id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name", IsNullable=true)]
        public string[] name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("systemRoles", IsNullable=true)]
        public string[] systemRoles {
            get {
                return this.systemRolesField;
            }
            set {
                this.systemRolesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://user.ws.blackboard/xsd")]
    public partial class PortalRoleVO {
        
        private string dataSourceIdField;
        
        private string descriptionField;
        
        private string[] expansionDataField;
        
        private string idField;
        
        private string roleNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dataSourceId {
            get {
                return this.dataSourceIdField;
            }
            set {
                this.dataSourceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expansionData", IsNullable=true)]
        public string[] expansionData {
            get {
                return this.expansionDataField;
            }
            set {
                this.expansionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string roleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://user.ws.blackboard/xsd")]
    public partial class AddressBookEntryVO {
        
        private UserExtendedInfoVO addressBookEntryField;
        
        private string[] expansionDataField;
        
        private string idField;
        
        private string titleField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserExtendedInfoVO addressBookEntry {
            get {
                return this.addressBookEntryField;
            }
            set {
                this.addressBookEntryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expansionData", IsNullable=true)]
        public string[] expansionData {
            get {
                return this.expansionDataField;
            }
            set {
                this.expansionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://user.ws.blackboard/xsd")]
    public partial class UserExtendedInfoVO {
        
        private string businessFaxField;
        
        private string businessPhone1Field;
        
        private string businessPhone2Field;
        
        private string cityField;
        
        private string companyField;
        
        private string countryField;
        
        private string departmentField;
        
        private string emailAddressField;
        
        private string[] expansionDataField;
        
        private string familyNameField;
        
        private string givenNameField;
        
        private string homeFaxField;
        
        private string homePhone1Field;
        
        private string homePhone2Field;
        
        private string jobTitleField;
        
        private string middleNameField;
        
        private string mobilePhoneField;
        
        private string stateField;
        
        private string street1Field;
        
        private string street2Field;
        
        private string webPageField;
        
        private string zipCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string businessFax {
            get {
                return this.businessFaxField;
            }
            set {
                this.businessFaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string businessPhone1 {
            get {
                return this.businessPhone1Field;
            }
            set {
                this.businessPhone1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string businessPhone2 {
            get {
                return this.businessPhone2Field;
            }
            set {
                this.businessPhone2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expansionData", IsNullable=true)]
        public string[] expansionData {
            get {
                return this.expansionDataField;
            }
            set {
                this.expansionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string familyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string givenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string homeFax {
            get {
                return this.homeFaxField;
            }
            set {
                this.homeFaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string homePhone1 {
            get {
                return this.homePhone1Field;
            }
            set {
                this.homePhone1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string homePhone2 {
            get {
                return this.homePhone2Field;
            }
            set {
                this.homePhone2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string jobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string street1 {
            get {
                return this.street1Field;
            }
            set {
                this.street1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string street2 {
            get {
                return this.street2Field;
            }
            set {
                this.street2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string webPage {
            get {
                return this.webPageField;
            }
            set {
                this.webPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://user.ws.blackboard/xsd")]
    public partial class UserRoleVO {
        
        private string[] expansionDataField;
        
        private string idField;
        
        private string insRoleIdField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expansionData", IsNullable=true)]
        public string[] expansionData {
            get {
                return this.expansionDataField;
            }
            set {
                this.expansionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string insRoleId {
            get {
                return this.insRoleIdField;
            }
            set {
                this.insRoleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.platform.blackboard/xsd")]
    public partial class VersionVO {
        
        private long versionField;
        
        private bool versionFieldSpecified;
        
        /// <remarks/>
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified {
            get {
                return this.versionFieldSpecified;
            }
            set {
                this.versionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://user.ws.blackboard/xsd")]
    public partial class ObserverAssociationVO {
        
        private string[] expansionDataField;
        
        private string[] observeeIdField;
        
        private string[] observeeIdByNameField;
        
        private string observerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expansionData", IsNullable=true)]
        public string[] expansionData {
            get {
                return this.expansionDataField;
            }
            set {
                this.expansionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("observeeId", IsNullable=true)]
        public string[] observeeId {
            get {
                return this.observeeIdField;
            }
            set {
                this.observeeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("observeeIdByName", IsNullable=true)]
        public string[] observeeIdByName {
            get {
                return this.observeeIdByNameField;
            }
            set {
                this.observeeIdByNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string observerId {
            get {
                return this.observerIdField;
            }
            set {
                this.observerIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://user.ws.blackboard/xsd")]
    public partial class UserVO {
        
        private System.Nullable<long> birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private string dataSourceIdField;
        
        private string educationLevelField;
        
        private string[] expansionDataField;
        
        private UserExtendedInfoVO extendedInfoField;
        
        private string genderTypeField;
        
        private string idField;
        
        private string[] insRolesField;
        
        private bool isAvailableField;
        
        private bool isAvailableFieldSpecified;
        
        private string nameField;
        
        private string passwordField;
        
        private string studentIdField;
        
        private string[] systemRolesField;
        
        private string titleField;
        
        private string userBatchUidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dataSourceId {
            get {
                return this.dataSourceIdField;
            }
            set {
                this.dataSourceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string educationLevel {
            get {
                return this.educationLevelField;
            }
            set {
                this.educationLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expansionData", IsNullable=true)]
        public string[] expansionData {
            get {
                return this.expansionDataField;
            }
            set {
                this.expansionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserExtendedInfoVO extendedInfo {
            get {
                return this.extendedInfoField;
            }
            set {
                this.extendedInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string genderType {
            get {
                return this.genderTypeField;
            }
            set {
                this.genderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("insRoles", IsNullable=true)]
        public string[] insRoles {
            get {
                return this.insRolesField;
            }
            set {
                this.insRolesField = value;
            }
        }
        
        /// <remarks/>
        public bool isAvailable {
            get {
                return this.isAvailableField;
            }
            set {
                this.isAvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isAvailableSpecified {
            get {
                return this.isAvailableFieldSpecified;
            }
            set {
                this.isAvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string studentId {
            get {
                return this.studentIdField;
            }
            set {
                this.studentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("systemRoles", IsNullable=true)]
        public string[] systemRoles {
            get {
                return this.systemRolesField;
            }
            set {
                this.systemRolesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userBatchUid {
            get {
                return this.userBatchUidField;
            }
            set {
                this.userBatchUidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void changeUserBatchUidCompletedEventHandler(object sender, changeUserBatchUidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changeUserBatchUidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changeUserBatchUidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool @return {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool returnSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getSystemRolesCompletedEventHandler(object sender, getSystemRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSystemRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSystemRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getUserCompletedEventHandler(object sender, getUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void saveObserverAssociationCompletedEventHandler(object sender, saveObserverAssociationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveObserverAssociationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveObserverAssociationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getServerVersionCompletedEventHandler(object sender, getServerVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getServerVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getServerVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VersionVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VersionVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getUserInstitutionRolesCompletedEventHandler(object sender, getUserInstitutionRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserInstitutionRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserInstitutionRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserRoleVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserRoleVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void changeUserDataSourceIdCompletedEventHandler(object sender, changeUserDataSourceIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changeUserDataSourceIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changeUserDataSourceIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool @return {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool returnSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void deleteObserverAssociationCompletedEventHandler(object sender, deleteObserverAssociationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteObserverAssociationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteObserverAssociationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void initializeUserWSCompletedEventHandler(object sender, initializeUserWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class initializeUserWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal initializeUserWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool @return {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool returnSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void deleteAddressBookEntryCompletedEventHandler(object sender, deleteAddressBookEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteAddressBookEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteAddressBookEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void saveAddressBookEntryCompletedEventHandler(object sender, saveAddressBookEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveAddressBookEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveAddressBookEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void deleteUserByInstitutionRoleCompletedEventHandler(object sender, deleteUserByInstitutionRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteUserByInstitutionRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteUserByInstitutionRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void deleteUserCompletedEventHandler(object sender, deleteUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getInstitutionRolesCompletedEventHandler(object sender, getInstitutionRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInstitutionRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInstitutionRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PortalRoleVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PortalRoleVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getAddressBookEntryCompletedEventHandler(object sender, getAddressBookEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAddressBookEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAddressBookEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddressBookEntryVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddressBookEntryVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getObserveeCompletedEventHandler(object sender, getObserveeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getObserveeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getObserveeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ObserverAssociationVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ObserverAssociationVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void saveUserCompletedEventHandler(object sender, saveUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591