// <auto-generated />
namespace Ecat.Data.Contexts
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Init_ECAT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_ECAT));
        
        string IMigrationMetadata.Id
        {
            get { return "201704201420271_Init_ECAT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
